// This file is generated by Slice Machine. Update with care!

import AlwaysForYouSection from './AlwaysForYouSection';
import BriefDescriptionSection from './BriefDescriptionSection';
import ContactUs from './ContactUs';
import HomePageLanding from './HomePageLanding';
import OurSpeciality from './OurSpeciality';
import ServicesSection from './ServicesSection';
import TeamCards from './TeamCards';
import Testimonials from './Testimonials';

export {
	AlwaysForYouSection,
	BriefDescriptionSection,
	ContactUs,
	HomePageLanding,
	OurSpeciality,
	ServicesSection,
	TeamCards,
	Testimonials,
};

export const components = {
	always_for_you_section: AlwaysForYouSection,
	brief_description_section: BriefDescriptionSection,
	contact_us: ContactUs,
	home_page_landing: HomePageLanding,
	our_speciality: OurSpeciality,
	services_section: ServicesSection,
	team_cards: TeamCards,
	testimonials: Testimonials,
};
