// This file is generated by Slice Machine. Update with care!

import AlwaysForYouSection from './AlwaysForYouSection';
import BriefDescriptionSection from './BriefDescriptionSection';
import HomePageLanding from './HomePageLanding';
import ServicesSection from './ServicesSection';

export { AlwaysForYouSection, BriefDescriptionSection, HomePageLanding, ServicesSection };

export const components = {
  always_for_you_section: AlwaysForYouSection,
  brief_description_section: BriefDescriptionSection,
  home_page_landing: HomePageLanding,
  services_section: ServicesSection,
};
