// This file is generated by Slice Machine. Update with care!

import HomePageLanding from './HomePageLanding';
import ServicesSection from './ServicesSection';

export { HomePageLanding, ServicesSection };

export const components = {
  home_page_landing: HomePageLanding,
  services_section: ServicesSection,
};
