#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '-----------------------------------------------------------------------'
echo '-- 🏗️👷 Styling, testing and building your project before committing  --'
echo '-----------------------------------------------------------------------'

# Check Prettier standards
yarn check-format ||
        (

                echo '----------------------------------------------------------------------'
                echo '🤢😰 Prettier Check Failed. Run yarn format, add changes and try commit again.'
                echo 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
                false
        )

# Check ESLint Standards
yarn check-lint ||
        (
                echo '----------------------------------------------------------------------'
                echo '🤯🥶 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
                echo 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
                false
        )

# Check tsconfig standards
yarn check-types ||
        (
                echo '----------------------------------------------------------------------'
                echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
                Make the changes required above.'
                echo 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
                false
        )

# If everything passes... Now we can commit
echo '----------------------------------------------------------------------'
echo '🤔🤔🤔🤔... Code looks good... Trying to build now. 🤔🤔🤔🤔'
echo '----------------------------------------------------------------------'

yarn build ||
        (
                echo '❌👷🔨❌ Your build failed ❌👷🔨❌
                         Next build failed: View the errors above to see why.'
                echo 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

                false
        )

# If everything passes... Now we can commit
echo ' ------------------------------------------------------------'
echo '|        ✅✅✅✅ YEAH, all test passed!!                     |'
echo '|        😁🤗 Begin comitting...... 👍👍                      |'
echo ' ------------------------------------------------------------'
